# Generated by Django 3.1.6 on 2021-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adjClose', models.FloatField()),
                ('volume', models.FloatField()),
                ('unadjustedVolume', models.FloatField()),
                ('change', models.FloatField()),
                ('changePercent', models.FloatField()),
                ('vwap', models.FloatField()),
                ('label', models.CharField(default='', max_length=10)),
                ('changeOverTime', models.FloatField()),
                ('companyId', models.IntegerField()),
            ],
        ),
    ]
